name: Bug Report
description: Report a bug!
title: "[Bug]: "
assignees: [Ducky07]
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproducing the bug
      description: Steps to reproduce the behavior.
      placeholder: Step 1:.. Step 2:... etc.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or a video to help explain your problem.
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Any additional context
      description: Add any other context about the problem.
      placeholder: Development environment, Operating System or anything else you'd like to mention.