name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
assignees: [Ducky07]
labels: [Feature]
body:
  - type: markdown
    attributes:
      value: |
        Suggest an idea or enhancement!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when ...
  - type: textarea
    id: request
    attributes:
      label: Describe a new solution or feature
      description: Clear and concise description of your solution or feature.
      placeholder: Describe a solution/feature you'd like
      value: "A new feature!"
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or a video to help explain your request.
  - type: textarea
    id: additional-context
    attributes:
      label: Any additional context
      description: Add any other details about your request.
      placeholder: Anything else you'd like to mention?
